services:

  python-pdf-reader:
    build:
      context: .
      dockerfile: pdftotext.Dockerfile
    volumes:
      - ./books:/books
      - ./app:/app
      - ./text:/text
    working_dir: /app
    environment:
      - PDF_FILE=${PDF_FILE:-""}
    command: ["python", "read.py", "$PDF_FILE"]
    # stdin_open: true
    # tty: true

  google-text-to-speech:
    build:
      context: .
      dockerfile: google.Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json
    volumes:
      # - TEXT_FILE=${TEXT_FILE}
      - ./secrets:/secrets
      - ./text:/text
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash